### ISSUE TITLE
Add pdf-viewer.js to the build

### ISSUE THREAD

**Issue by web-padawan** [bundled-es-modules/pdfjs-dist#2]
Hi, we have been evaluating this project to get ES module version of `pdf.js` in order to make a web component wrapper for it. So I would like to request a build for `pdf-viewer.js` (currently missing).

I'm going to try updating the Rollup config to make this happen, and then submit a PR.

**Comment by daKmoR** [comment]
awesome 💪 

@robrez be prepared 😛

**Comment by robrez** [comment]
What we have now is too closely focused on just the `build` directory of the pdfjs-dist repo.  Many consumers of pdfjs-dist probably want `web/*`.  I'm not sure how much utility might exist in some of the other dirs (external, image_decoders, lib, etc)

I've just noticed that pdfjs has published another release - v2.1.266 (2 days ago)

**Comment by robrez** [comment]
Worth noting, too, that I've been meaning to research (this)[https://github.com/mozilla/pdfjs-dist/blob/master/build/pdf.js#L9931] region.  I think it makes the es bundle much larger than it really ought to be by bundling what really ought to be an "import"

```javascript
worker = require('./pdf.worker.js');
```

**Comment by robrez** [comment]
Update:

@datori has been working on resolving all of the concerns above.  he has submitted a PR: 
 https://github.com/bundled-es-modules/pdfjs-dist/pull/4

I've just left a few review comments -- but feel good about the PR as a whole.  Feel free to provide additional review!

**Comment by web-padawan** [comment]
Thanks! Will take a look soon.

**Comment by robrez** [comment]
Merged #4 , published `@bundled-es-modules/pdfjs-dist#2.0.943-viewer`.  We've tested this version -- using the new "viewer" addition specifically -- in a `polymer build` and an `ng build` with nice results.  Thanks @datori 

Pending more feedback, we can bump to pdfjs v2.1.266 and publish an rc

**Comment by robrez** [comment]
Closing as resolved, internal testing and feedback has been positive
