### ISSUE TITLE
Update to pdf.js 2.1.266 to work in IE11

### ISSUE THREAD

**Issue by web-padawan** [bundled-es-modules/pdfjs-dist#5]
Can we update pdf.js, including the viewer, to a latest version? This would solve some problems with IE11 especially related to `Symbol.iterator` used in current bundle.

See https://github.com/vaadin/vaadin-pdf-viewer/issues/23#issuecomment-475279676 for details.

**Comment by robrez** [comment]
Can do, thanks for the info

**Comment by robrez** [comment]
Thanks for the PR @datori 

- Merged #6 
- Created tag v2.1.266-rc a
- v2.1.266-rc to npm

Let us know if we need to re-open the issue for any reason

**Comment by web-padawan** [comment]
Thanks for the quick feedback. We will try it out.

One thing which could be still tricky to get working is that `pdf-worker.js` brings Symbol polyfill from `core-js` which is conflicting with polyfill included in webcomponentsjs. 

This issue should be fixed in webcomponentsjs, and has been reported many times.

**Comment by robrez** [comment]
Yeah that could get tricky.  Let me think on that one.

In the meantime, I added my 👍 to https://github.com/webcomponents/webcomponentsjs/issues/1007
