### ISSUE TITLE
rollup optimization removes if condition block

### ISSUE THREAD

**Issue by hei-pa** [bundled-es-modules/pdfjs-dist#7]
https://github.com/bundled-es-modules/pdfjs-dist/blob/597a62cb96ba8662df18c280695e721ec846433f/build/pdf.js#L19231

You run into this [https://github.com/rollup/rollup/issues/2326](https://github.com/rollup/rollup/issues/2326)

The final build is missing an if condition, but the if body still exists and throws always.

To solve this simply update the used rollup version to 1.11.3

**Comment by robrez** [comment]
Thank you, will look into it

**Comment by robrez** [comment]
Thanks again for the help, sorry it took so long to get around to this.

- bumped rollup dependency version to `^1.0.0`
- tagged v2.1.266
- published to npm

Confirmed the code code now contains that missing `if` condition:

```javascript
function getShadingPatternFromIR(raw) {
  var shadingIR = ShadingIRs[raw[0]];

  if (!shadingIR) {
    throw new Error("Unknown IR type: ".concat(raw[0]));
  }
```
