### ISSUE TITLE
Any plans for Typescript types?

### ISSUE THREAD

**Issue by mikecousins** [bundled-es-modules/pdfjs-dist#8]
Do you guys have any plans for this?

**Comment by robrez** [comment]
Oh that sounds nice, but, I'm not sure if there are any great options at our disposal since we just use rollup to transpile pdfjs.  Let me brew on that for a bit.  My gut feeling is that the best we could do is manually code `d.ts` files

PRs, suggestions are welcomed

**Comment by robrez** [comment]
this looks promising -- https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/pdfjs-dist

not sure if it would be better to provide some documentation recommending it or to pull it in as a dependency and copy the files as part of our distribution

**Comment by mikecousins** [comment]
Oooh that's sweet. I'd probably pull it in so that it matches the import properly.

**Comment by robrez** [comment]
Re-exporting the types vended by pdfjs-dist via [^3.6.172-alpha.1](https://github.com/bundled-es-modules/pdfjs-dist/pull/30/commits/26577c23f689d8ddd0e623047fba27f1b46ef893)
