### ISSUE TITLE
publish pdfjs-dist-v2.2.228

### ISSUE THREAD

**Issue by robrez** [bundled-es-modules/pdfjs-dist#9]
pdfjs-dist published v2.2.228 back in July. need to investigate

**Comment by mikecousins** [comment]
Any progress on this?

**Comment by robrez** [comment]
Ooof, thanks for the reminder.

I did try a quick upgrade a few weeks back and there were a couple unnamed exports colliding that I've been meaning to track down

Will try and take a look this weekend

**Comment by mikecousins** [comment]
Awesome, thanks man!

**Comment by robrez** [comment]
Okay, my recollection was a bit off. I did have trouble but it was w/ upgrading a dev-dependency relating to rollup

I've just tagged `v2.2.228-alpha1` and pushed it to npm

I'm going to keep this issue open for a bit incase any issues pop up

**Comment by mikecousins** [comment]
Seems to work well so far. Thanks for your help!
